# Generated by Django 2.2.19 on 2021-07-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20210620_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='average_consumption',
            field=models.FloatField(null=True, verbose_name='Consumo medio del coche a los 100L'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=models.CharField(max_length=512, null=True, verbose_name='Descripción del coche'),
        ),
    ]
