# Generated by Django 2.2.19 on 2021-07-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_remove_carmodel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.CarModel', verbose_name='Coche asociado a esta imagen'),
        ),
    ]
