# Generated by Django 2.2.19 on 2021-07-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_auto_20210703_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='description',
        ),
    ]
