# Generated by Django 2.2.19 on 2021-07-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_remove_carmodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'CarModel'},
        ),
    ]
