# Generated by Django 2.2.19 on 2021-05-29 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_surname', models.CharField(max_length=64, verbose_name='Primer apellido')),
                ('second_surname', models.CharField(max_length=64, verbose_name='Segundo apellido')),
                ('birthdate', models.DateTimeField(verbose_name='Fecha de nacimiento del usuario')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
