# Generated by Django 2.2.19 on 2021-06-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dni',
            field=models.CharField(max_length=9, null=True, verbose_name='Documento de identificación nacional'),
        ),
    ]
