# Generated by Django 2.2.19 on 2021-06-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phoneNumber',
            field=models.CharField(max_length=32, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(verbose_name='Fecha de nacimiento del usuario'),
        ),
    ]
