# Generated by Django 2.2.19 on 2021-06-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210610_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
