# Generated by Django 2.2.19 on 2021-06-19 23:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210610_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
