# Generated by Django 2.2.19 on 2021-06-19 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinfo_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
