# Generated by Django 2.2.19 on 2021-07-14 22:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210619_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento del usuario'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_surname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='second_surname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rights', models.FileField(blank=True, null=True, upload_to='access_right/')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='user.UserInfo', verbose_name='Usuario')),
            ],
        ),
    ]
