# Generated by Django 2.2.19 on 2021-07-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210714_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'UserInfo'},
        ),
    ]
