# Generated by Django 2.2.19 on 2021-06-16 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0004_modelreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('monthly_cost', models.IntegerField(null=True, verbose_name='Coste mensual del contrato')),
                ('annual_mileage', models.IntegerField(null=True, verbose_name='Kilometraje anual del contrato')),
                ('duration', models.IntegerField(null=True, verbose_name='Duración del contrato')),
                ('start_date', models.DateField(verbose_name='Fecha de creación')),
                ('reject_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización unilateral')),
                ('bank_account', models.CharField(max_length=64, verbose_name='Número de cuenta bancaria')),
                ('status', models.CharField(choices=[('C', 'Continue'), ('F', 'Finish'), ('R', 'Reject')], default='C', max_length=1, null=True, verbose_name='Estado')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='car.CarModel', verbose_name='Modelo de coche asociado al contrato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Cliente asociado al contrato')),
            ],
        ),
    ]
