# Generated by Django 2.2.19 on 2021-06-16 19:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cost', models.IntegerField(verbose_name='Coste de la multa')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='contract.Contract', verbose_name='Contrato asociado a la multa')),
            ],
        ),
    ]
