# Generated by Django 2.2.19 on 2021-07-04 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de activación'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('E', 'En proceso'), ('A', 'Activo'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='E', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
