# Generated by Django 2.2.19 on 2021-07-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20210704_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('E', 'En proceso'), ('A', 'Activo'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='E', max_length=1, verbose_name='Estado'),
        ),
    ]
