# Generated by Django 2.2.19 on 2021-07-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_auto_20210704_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de activación'),
        ),
    ]
