# Generated by Django 2.2.19 on 2021-07-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20210707_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='car_color',
            field=models.CharField(default='red', max_length=30, verbose_name='Color del modelo del coche'),
            preserve_default=False,
        ),
    ]
