# Generated by Django 2.2.19 on 2021-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_contract_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='description',
            field=models.CharField(default='descripcion', max_length=30, verbose_name='Texto descriptivo de la incidencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fine',
            name='pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
    ]
