# Generated by Django 2.2.19 on 2021-07-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_auto_20210715_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
