# Generated by Django 2.2.19 on 2021-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_contract_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='monthly_cost',
            field=models.FloatField(null=True, verbose_name='Coste mensual del contrato'),
        ),
    ]
