# Generated by Django 2.2.19 on 2021-07-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_auto_20210717_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='creation_date',
        ),
    ]
