# Generated by Django 2.2.19 on 2021-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_remove_contract_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='contract',
            name='reject_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
    ]
