# syntax=docker/dockerfile:1
FROM python:3.6.13
ENV PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y build-essential && apt-get clean && apt-get autoremove -y
WORKDIR /project/backend/
COPY requirements.txt /project/backend/
RUN pip install --upgrade pip==21.0.1 && pip install -r requirements.txt
COPY ./ /project/
